version: "2.2"

services:
  db:
    image: postgres:13.3-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: tradelogger
    command: postgres -c fsync=off
