default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: tradelogger
  password: tradelogger
  pool: 5

development:
  <<: *default
  database: trade_logger_development

test:
  <<: *default
  database: trade_logger_test
