default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  url: postgresql://user:tradelogger@127.0.0.1:5432/trade_logger_development

test:
  <<: *default
  url: postgresql://user:tradelogger@127.0.0.1:5432/trade_logger_test
